# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibo_nums(up_to)
    fibs = [1]
    num = 2
    while num < up_to
        push!(fibs, num)
        num = fibs[end] + fibs[end-1]
    end
    return fibs
end

function add_evens(arr)
    return sum([x for x in arr if x % 2 == 0])
end

fibo_nums(4_000_000) |> add_evens
